### ISSUE TITLE
Random gib on landing as nightmare

### ISSUE THREAD

**Issue by itsmeow** [Rukofamicom/Royale-Station-13#51]
Random gib on landing as nightmare

![image](https://user-images.githubusercontent.com/10366817/226467320-a318f017-ec60-492f-b1a6-cd0ccf342845.png)
![image](https://user-images.githubusercontent.com/10366817/226467325-c248eecf-bc9c-4dc5-9e53-f1a6ef143cc0.png)

Round 6898

![image](https://user-images.githubusercontent.com/10366817/226467582-4c0011e1-b9ac-420c-a45e-b88ca585d648.png)

**Comment by itsmeow** [comment]
Also corg's alert level distances seem wrong, it was declaring delta when the wall finally reached bridge.

**Comment by Rukofamicom** [comment]
The bridge is off-center for delta would be my guess for that

The center area for the walls is always the same, dead center of the Z-level
